--- 
title: "Covid Travel"
author: "Minwoo CHOI - mc5061<br>Pranav Gopal - pg2685<br>Daniel Schmidle - dps2150"
date: "2021-04-12"
site: bookdown::bookdown_site
---

# Introduction

According to data from the New York Times, as of early April 2021 there have been over 550,000 total deaths in the U.S. from COVID-19. Early 2020 marked a period of instability in our lives, but if one thing is certain, it is that  the past year has been rife with contrasting political and philosophical views. As COVID-19 spread in early 2020, stay at home orders were implemented, removed, implemented again, or never put into place at all throughout the United States. People believed or denied, were scared or indifferent, and were generally confused about the entire situation. And through the uncertainty, the novel virus exploited the structural weaknesses within society. <br><br>
 
Thus, this project takes a retrospective look at how the virus spread within the United States by the actions (or inactions) of mobility by the population. Did the Stay At Home Orders work? Did the amount of travel in regions affect the spread of the virus? How did air travel affect the spread? To find out, let us look at the spread of the virus correlated with regional mobility of individuals traveling within the United States.



