<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Missing values | Covid Travel</title>
  <meta name="description" content="Chapter 4 Missing values | Covid Travel" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Missing values | Covid Travel" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Missing values | Covid Travel" />
  
  
  

<meta name="author" content="Daniel Schmidle - dps2150   Minwoo CHOI - mc5061   Pranav Gopal - pg2685" />


<meta name="date" content="2021-04-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-transformation.html"/>
<link rel="next" href="results.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="data-sources.html"><a href="data-sources.html"><i class="fa fa-check"></i><b>2</b> Data sources</a></li>
<li class="chapter" data-level="3" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>3</b> Data transformation</a></li>
<li class="chapter" data-level="4" data-path="missing-values.html"><a href="missing-values.html"><i class="fa fa-check"></i><b>4</b> Missing values</a></li>
<li class="chapter" data-level="5" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>5</b> Results</a><ul>
<li class="chapter" data-level="5.1" data-path="results.html"><a href="results.html#covid-19-in-the-united-states"><i class="fa fa-check"></i><b>5.1</b> Covid-19 in the United States</a></li>
<li class="chapter" data-level="5.2" data-path="results.html"><a href="results.html#mobility-and-covid-19"><i class="fa fa-check"></i><b>5.2</b> Mobility and Covid-19</a></li>
<li class="chapter" data-level="5.3" data-path="results.html"><a href="results.html#air-travel-and-covid-19"><i class="fa fa-check"></i><b>5.3</b> Air Travel and Covid-19</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>6</b> Interactive component</a></li>
<li class="chapter" data-level="7" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>7</b> Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Covid Travel</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-values" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Missing values</h1>
<p>The only dataset with missing values was the Trips by Distance data from the U.S. DOT Bureau of Transportation Statistics.</p>
<p>So, working with that set, let us find some NA’s</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
level
</th>
<th style="text-align:left;">
na_s
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Number of NA’s National:
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of NA’s State:
</td>
<td style="text-align:left;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of NA’s County:
</td>
<td style="text-align:left;">
5779
</td>
</tr>
</tbody>
</table>
<p>We can see here that the NA values only occur at the county level. So, let’s find out where those NA’s are hiding.</p>
<pre><code>##       Date              State.FIPS        State         County.FIPS   
##  Min.   :2020-01-22   Min.   : 1.00   TX     :109474   Min.   : 1001  
##  1st Qu.:2020-05-08   1st Qu.:18.00   GA     : 68529   1st Qu.:18177  
##  Median :2020-08-24   Median :29.00   VA     : 57323   Median :29176  
##  Mean   :2020-08-24   Mean   :30.28   KY     : 51720   Mean   :30384  
##  3rd Qu.:2020-12-10   3rd Qu.:45.00   MO     : 49565   3rd Qu.:45081  
##  Max.   :2021-03-27   Max.   :56.00   KS     : 45255   Max.   :56045  
##                                       (Other):972336                  
##                County        Population.Staying.at.Home
##  Washington County:  12930   Min.   :     10           
##  Jefferson County :  10775   1st Qu.:   2185           
##  Franklin County  :  10344   Median :   5221           
##  Jackson County   :   9913   Mean   :  25984           
##  Lincoln County   :   9913   3rd Qu.:  15053           
##  Madison County   :   8189   Max.   :4131225           
##  (Other)          :1292138   NA&#39;s   :5779              
##  Population.Not.Staying.at.Home Number.of.Trips    Number.of.Trips..1
##  Min.   :    117                Min.   :     227   Min.   :       0  
##  1st Qu.:   8826                1st Qu.:   37386   1st Qu.:    8051  
##  Median :  20719                Median :   88712   Median :   19530  
##  Mean   :  78593                Mean   :  325210   Mean   :   82383  
##  3rd Qu.:  54017                3rd Qu.:  231308   3rd Qu.:   52890  
##  Max.   :8636354                Max.   :43031242   Max.   :12335889  
##  NA&#39;s   :5779                   NA&#39;s   :5779       NA&#39;s   :5779      
##  Number.of.Trips.1.3 Number.of.Trips.3.5 Number.of.Trips.5.10 Number.of.Trips.10.25
##  Min.   :       0    Min.   :      0     Min.   :      0      Min.   :      0      
##  1st Qu.:    8345    1st Qu.:   3548     1st Qu.:   4909      1st Qu.:   5829      
##  Median :   21520    Median :   9989     Median :  12433      Median :  13901      
##  Mean   :   80587    Mean   :  39327     Mean   :  49127      Mean   :  47670      
##  3rd Qu.:   57947    3rd Qu.:  28213     3rd Qu.:  34078      3rd Qu.:  35061      
##  Max.   :11401040    Max.   :5423126     Max.   :6535454      Max.   :5844180      
##  NA&#39;s   :5779        NA&#39;s   :5779        NA&#39;s   :5779         NA&#39;s   :5779         
##  Number.of.Trips.25.50 Number.of.Trips.50.100 Number.of.Trips.100.250
##  Min.   :      0       Min.   :     0         Min.   :     0         
##  1st Qu.:   3013       1st Qu.:  1184         1st Qu.:   424         
##  Median :   6412       Median :  2598         Median :   967         
##  Mean   :  16454       Mean   :  6086         Mean   :  2678         
##  3rd Qu.:  14435       3rd Qu.:  5742         3rd Qu.:  2301         
##  Max.   :1859953       Max.   :555732         Max.   :356594         
##  NA&#39;s   :5779          NA&#39;s   :5779           NA&#39;s   :5779           
##  Number.of.Trips.250.500 Number.of.Trips...500
##  Min.   :    0.0         Min.   :     0.0     
##  1st Qu.:   57.0         1st Qu.:    11.0     
##  Median :  166.0         Median :    41.0     
##  Mean   :  574.5         Mean   :   323.7     
##  3rd Qu.:  442.0         3rd Qu.:   150.0     
##  Max.   :90947.0         Max.   :125691.0     
##  NA&#39;s   :5779            NA&#39;s   :5779</code></pre>
<p>From the summary we can see that there is an equal 5779 NA’s for each numeric column thus, upon further inspection, 5779 rows are fully incomplete for trips data. So, let’s isolate those rows.</p>
<p>Frist, since this data is a timeseries, let’s check the dates to see if there is a pattern.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Date
</th>
<th style="text-align:right;">
count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2021-03-26
</td>
<td style="text-align:right;">
1228
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-11-29
</td>
<td style="text-align:right;">
113
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-09-06
</td>
<td style="text-align:right;">
101
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-04
</td>
<td style="text-align:right;">
99
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-03
</td>
<td style="text-align:right;">
93
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-02
</td>
<td style="text-align:right;">
91
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-09-07
</td>
<td style="text-align:right;">
88
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-01
</td>
<td style="text-align:right;">
87
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-06-30
</td>
<td style="text-align:right;">
85
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-06-29
</td>
<td style="text-align:right;">
79
</td>
</tr>
</tbody>
</table>
<p>From this we see the vast majority of NA occur on 2021-03-26, which is one day before the ending day of the dataset. Thus, we can conclude that the rows for second to last day have been created for data input but have not updated by the time of data procurement. Thus, removing the last two days from the dataset will reduce potential error and will not affect analysis of mobility on COVID-19 rates from January 2020 to March 2021. Now to get the total number of days in the dataset.</p>
<pre><code>## Time difference of 428 days</code></pre>
<p>Here we can see that there are 428 total days in the dataset so, lets narrow down the search to counties with &gt; 10% of missing data. (10% is chosen because 90% of available data could still provide accurate insights for trips data) here is a sample:</p>
<table>
<thead>
<tr class="header">
<th align="left">State</th>
<th align="left">County</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AK</td>
<td align="left">Aleutians East Borough</td>
<td align="right">62</td>
</tr>
<tr class="even">
<td align="left">AK</td>
<td align="left">Bristol Bay Borough</td>
<td align="right">353</td>
</tr>
<tr class="odd">
<td align="left">AK</td>
<td align="left">Haines Borough</td>
<td align="right">101</td>
</tr>
<tr class="even">
<td align="left">AK</td>
<td align="left">Lake and Peninsula Borough</td>
<td align="right">295</td>
</tr>
<tr class="odd">
<td align="left">AK</td>
<td align="left">Skagway Municipality</td>
<td align="right">141</td>
</tr>
<tr class="even">
<td align="left">AK</td>
<td align="left">Yakutat City and Borough</td>
<td align="right">395</td>
</tr>
</tbody>
</table>
<p>There are 22 counties with high rates of NA values. Thus, these are the counties that could be most problematic when analyzing at a county scale. So, lets save the data frame of these top NA violators for future reference when further micro analysis is desired within these areas.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">save</span>(high.na, <span class="dt">file=</span><span class="st">&quot;high_NA_areas.RDS&quot;</span>)</a></code></pre></div>
<p>Now to consider, would the NA values from certain counties affect State level analysis? To find out let’s plot the states with county NA values.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Here we can see the states with the majority of the NA values, lets pick the top 5 (AK, NE, MT, TX, HI) and see how much the NA values might impact the aggregate state values.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>We can see by the above stacked bar plot that the NA values account for a negligible amount of total values from each of the top NA states. Thus, the NA values should be of note, but of not much concern when considering total trips by distance for each state. <br></p>
<p>With this analysis of NA values, the decision to leave the NA rows in the dataset is made for continuity of county timelines.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-transformation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dps2150/COVIDtravel/edit/main/04-missing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/dps2150/COVIDtravel/blob/main/04-missing.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
